### ISSUE TITLE
date calculation edge case

### ISSUE THREAD

**Issue by nickslick03** [nickslick03/messiah-meal-planner#56]
it's a pretty extraneous error but if you reset the site and type '7777'  in the start date which results in the date 07/07/0077 the getDatesBetween function throws a stack overflow error, I assume it has something with the end date not being set so a possible solution could be default values. We could aslo set min and max values on the dates

**Comment by cdrice26** [comment]
Yeah I think setting min/max values on the dates makes sense. The getAllDatesBetween function returns an array of every date between two dates, so if the date range is that big it could certainly cause issues...for instance, with that exact date for the start date and today as the end date, you'd be returning an array with over 700,000 elements, which is bound to cause issues regardless. So we should probably have the min/max of each element only allow going a few years either direction (even just 1 or 2).

**Comment by nickslick03** [comment]
So I just tested a date input element with min and max values and it doesn't keep you from typing in dates outside the range unless the different differentiators (month, day, year) are the same in the min and max, so min and max won't help. I think the best fix is to make the getDatesBetween function iterative.

**Comment by cdrice26** [comment]
Okay got it. I think we would still have a similar issue with making it iterative though as it would still be returning an array of over 700,000 dates in the scenario you provided, which could still cause issues and some serious lag if the user enters particularly distant dates since this array is later passed into an iterator. The ```getAllDatesBetween``` function is only used to calculate the day when the meal plan runs out, so since it's not expected the user would try to plan a meal plan lasting thousands of years, I think it's fine to just disable this feature if the recursion depth is too high. I've tested a try/catch that just hides this result if the function errors and it seems to work, I can take the issue and create a PR if that approach sounds good to you.

**Comment by nickslick03** [comment]
yeah, honestly it's an edge case so we shouldn't need to do that much, that sounds excellent 👍

**Comment by cdrice26** [comment]
Alright I will do that.

**Comment by cdrice26** [comment]
I did test an iterative version just out of curiosity, while it does avoid the error, it also does cause the app to temporarily freeze and sometimes sets the dates to something arbitrary, so given that we can't prevent the users from entering outlandish dates, implementing a guard against feeding that into an iterator is probably smart.
